---

#knobs:
    # log_level_debug: true
    # log_to_console: false
mqtt:
    host: 192.168.0.143
    client_id: mqtt2wiz
    #username:
    #password:
    #reconnect_interval:

globals:
    topic_format: /{}/

devices:
    gu10_1:
        host: 192.168.0.188
        #topic:
    gu10_2:
        host: 192.168.0.131
    gu10_3:
        host: 192.168.0.183
    gu10_4:
        host: 192.168.0.101
    gu10_5:
        host: 192.168.0.127
    gu10_6:
        host: 192.168.0.161
    gu10_7:
        host: 192.168.0.107
    gu10_8:
        host: 192.168.0.149
    gu10_9:
        host: 192.168.0.120
    stairs_1:
        host: 192.168.0.180
    stairs_2:
        host: 192.168.0.168
    stairs_3:
        host: 192.168.0.124
    stairs_4:
        host: 192.168.0.130
    stairs_5:
        host: 192.168.0.136
    stairs_6:
        host: 192.168.0.119
    stairs_7:
        host: 192.168.0.126

...
